# Generated by Django 3.0 on 2019-12-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(max_length=200, verbose_name='Nome do Pet')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo do Pet')),
                ('raca', models.CharField(max_length=20, verbose_name='Raça do Pet')),
                ('tamanho', models.CharField(max_length=20, verbose_name='Tamanho do Pet')),
                ('cor', models.CharField(max_length=20, verbose_name='Cor do Pet')),
                ('dt_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('id_tutor', models.IntegerField(verbose_name='Tutor')),
                ('pet_alergico', models.BooleanField(blank=True, null=True)),
                ('pet_cardiaco', models.BooleanField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('cadastro', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['pet'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor', models.CharField(max_length=200, verbose_name='Nome do Tutor')),
                ('tel_principal', models.CharField(max_length=20, verbose_name='Telefone Principal')),
                ('tel_alternativo', models.CharField(max_length=20, verbose_name='Telefone Alternativo')),
                ('email', models.CharField(max_length=80, verbose_name='E-mail')),
                ('cont_alternativo', models.CharField(max_length=200, verbose_name='Contato Alternativo')),
                ('tel_contato', models.CharField(max_length=20, verbose_name='Telefone do Contato')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('cadastro', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
                'ordering': ['tutor'],
            },
        ),
    ]
