# Generated by Django 3.0 on 2019-12-09 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='id_tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_tutor', to='agenda.Tutor'),
        ),
    ]
