# Generated by Django 3.0 on 2019-12-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20191209_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='tamanho',
            field=models.CharField(max_length=20, null=True, verbose_name='Tamanho do Pet'),
        ),
    ]
