# Generated by Django 3.0 on 2019-12-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_auto_20191209_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamanhos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=10, verbose_name='Tamanho do Pet')),
            ],
            options={
                'verbose_name': 'Tamanho',
                'verbose_name_plural': 'Tamanho',
                'ordering': ['descricao'],
            },
        ),
    ]
