# Generated by Django 3.0 on 2019-12-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20191209_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tamanhos',
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['tutor', 'pet'], 'verbose_name': 'Pet', 'verbose_name_plural': 'Pets'},
        ),
        migrations.AlterField(
            model_name='pet',
            name='tamanho',
            field=models.CharField(max_length=20, null=True, verbose_name='Tamanho do Pet'),
        ),
    ]
