# Generated by Django 3.0 on 2019-12-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_auto_20191209_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raca', models.CharField(max_length=100, verbose_name='Raça do Pet')),
                ('porte', models.CharField(max_length=20, null=True, verbose_name='Porte do Pet')),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
                'ordering': ['raca', 'porte'],
            },
        ),
    ]
