# Generated by Django 3.0 on 2019-12-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_raca'),
    ]

    operations = [
        migrations.AddField(
            model_name='raca',
            name='tipo',
            field=models.CharField(max_length=20, null=True, verbose_name='Tipo do Pet'),
        ),
    ]
