# Generated by Django 3.0 on 2019-12-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_raca_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raca',
            name='tipo',
            field=models.CharField(max_length=20, verbose_name='Tipo do Pet'),
        ),
    ]
