# Generated by Django 3.0 on 2019-12-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_auto_20191211_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
    ]
