# Generated by Django 3.0 on 2019-12-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['servico'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
    ]
